spring:
  application:
    name: LifeArch

  datasource:
    url: jdbc:postgresql://localhost:5432/planner
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate # STRICTLY validate. Let Flyway manage the schema.
    open-in-view: false

  security:
    user:
      password: ${SPRING_SECURITY_PASSWORD}

  flyway:
    enabled: true

  main:
    banner-mode: off

application:
  security:
    jwt:
      # A 256-bit Hex encoded string (Keep this secret in production via environment variables)
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration-ms: 86400000 # 24 hours in milliseconds
