spring:
  application:
    name: LifeArch

  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate # STRICTLY validate. Let Flyway manage the schema.
    open-in-view: false

  security:
    user:
      password: ${SPRING_SECURITY_PASSWORD}

  flyway:
    enabled: true

  main:
    banner-mode: off

application:
  security:
    jwt:
      # A 256-bit Hex encoded string (Keep this secret in production via environment variables)
      secret-key: ${JWT_SECRET_KEY}
      expiration-ms: 86400000 # 24 hours in milliseconds

github:
  client-id: ${GITHUB_CLIENT_ID}
  client-secret: ${GITHUB_CLIENT_SECRET}
  redirect-uri: ${GITHUB_REDIRECT_URI}

app:
  frontend:
    url: ${FRONTEND_URL}
